dyne/tomb

extras/po/Makefile, extras/po/generate_translatable_strings.pl
The new script adds reference and context to the strings, identifies
them with more correctness and has blacklisting capabilities to ignore
strings that need no translation.
I'm unsure about the context that should be included with the strings, right now it's just the surrounding lines.
@hellekin @jaromil What do you think?
=> [i18n] New .pot file generation script

README.md, doc/TODO.org, tomb
Please see the updated dual behavior.
=> Detect plain swaps on encrypted partition (util-linux >= 2.22) or advise user to use -f (fixes #163)

tomb
Exactly what it says on the tin!
=> Fix comment typo: --use-random => --use-urandom

tomb
Some things I noticed while skimming through the file.
The whitespace issue was on line 319 to 324 (real tab and whitespace mixed). I hope the indention is the way it should be
=> Correct spelling and whitespaces

extras/translations/de.po, extras/translations/es.po, extras/translations/fr.po, extras/translations/generate_translatable_strings.pl, extras/translations/it.po, extras/translations/ru.po, extras/translations/sv.po, extras/translations/tomb.pot, tomb
Hey @jaromil,
Sorry I had some issues and couldn't do this before.
I made a PR so you can review it, just in case I messed up somewhere, as I did it in a hurry 😅
=> Sync translations with POEditor

extras/tomber/tomber/test.py, extras/tomber/tomber/tomber.py
=> Update tomber in extras for v2.2+

tomb
These are just a few simple corrections of grammatical errors I noticed recently in Tomb's output.
=> Fix 3 grammatical errors.

ChangeLog.md
=> changelog: fix minor typo

tomb
On my trial to create a zsh_completion file (a better one than I maintain in the AUR tomb-git package at least) I noticed some stuff (see #299 and #300 and some more which I need to address yet).
So some small commits for various things and up to debate.
Commit 2 and 4 could be combined as they touch the same subject, which I will do, if commit 4 is accepted.
Or 2,3 and 4 combined in one commit as a small overhaul of list_gnupg_ciphers(). Whatever is prefered.
Edit: Ah, and against suggesting changes on _list_optional_tools() I won't touch it anytime soon. Some commands only know `-v`, some only the long-option `--version` and some don't know about either of those two.
And changing it to a copy of hard-deps version checking isn't worth time spending on. Although it would be nice to see …
=> Small things

tomb
Fixes #335 and a typo, and prints a newline after conditional messages only when necessary.
=> Improve usage message

tomb
Bug fix for issue #328 tested with cryptsetup 2.1.0.
=> Bug fix #328

tomb
=> make gettext optional in _sudo()

tomb
=> use getent with wrappers every /etc/passwd query

INSTALL.md, doc/tomb.1
Fixed small typos in the documentation
=> Fixed documentation

tomb
testing a small refactor
simplified function calls for tracking of loop mount by using global
variables whose scope is limited to execution, most computation is now
included in the `is_valid_tomb` function.
=> refactor of state tracking for loop mounting

tomb
Fixes #416
Not sure if I used the best approach to solve this, if not, please let me know.
=> Make tomb open with -q quiet, fixes #416

INSTALL.md, KNOWN_BUGS.md, README.md, doc/KEY_SPECIFICATIONS.txt, doc/LinuxHDEncSettings.txt
Noticed a typo and did a spellcheck over the rest of the project.
Begrudgingly let the British spelling slide.
=> Correct some typos

tomb
Improve `--sudo` flag usage and error reporting and support for `doas`
=> Sudo loopback improve

tomb
=> Update copyright lines

tomb
Part of 653609a got reverted after a rebase.
=> Fixup: remove dead slam code

extras/translations/co.po, extras/translations/es.po, extras/translations/fi.po, extras/translations/it.po, extras/translations/zh_Hans.po
Replaces #550
Manual merge with resolved conflicts.
Should resolve the stuck situation with the diverged repos.
=> Weblate merge conflict

tomb
Mostly about plocate/mlocate.
The tool wasn't listed as optional or required and checks in index() and search() could be simplified and unified.
=> search/index: change handling of required deps
