- tomb
Commit 5dbcabdf2636300f6877e6bab27ef51c7b739a8f removed the `chown` call in `_tmp_create()` but not the associated error message. This commit removes that error message since it is just dead code.
> Remove outdated error message

- tomb
This block is already wrapped in the `else` block of the same test for the `$DISPLAY` variable, so this test is redundant.
> Remove redundant test for $DISPLAY

- doc/tomb.1
- tomb
Both the code and the documentation were incorrect about --kdf.
The code was using an iteration time much inferior to the one that the user could be expecting. The output messages were even more confusing, calling "count" what was actually "time".
The same error was present in the man page.
This commit tries to fix both of them.
This will close #192
> FIX errors on kdf iteration count

- tomb
The `exhumedkey` variable is initialized but never used, so this PR removes it. The comment removed by this PR is inaccurate. (The following line does not print the password.)
> Two minor one-line fixes

- doc/tomb.1
Mostly intended to fix the URLs at the end of the man-page.
The original page for dm-crypt pointed to the google-code page of cryptsetup and the google-code page itself redirects the user to gitlab, where the project is now hosted.
So replaced the URLs with their gitlab counterpart.
I inserted the extra .br because of the long URL. Without it those get fragmented even on larger terminal windows. But dunno if's that wise?
Made a note about the mount behaviour which got enhanced by ca012e8
Additionally some smaller typos corrected
> Man-Page: Small fixes

- extras/PYTHON.md
I noticed this small error, while I skimmed through the extras folder.
On another note. The tomber lib is out of sync with upstream (dunno what version was integrated with this repo (I assume 1.0.1)), but upstream is at 1.0.2 now.
Wouldn't it be easier to integrate tomber as a submodule?
Edit: Or as a subtree (maybe it's done like that. But it's hard to tell from the outside or is there a method to check for those?)
> extras: fix tomber repository URL

- tomb
In relation to #229, I found the current message to be a bit ambiguous. When I first started using Tomb, I wasn't sure if the success message was a good one or a bad one. Hopefully a clearer message will let new users understand that their swap is encrypted.
> Changed message when encrypted swap found to something more informative

- tomb
LSOF would be set everytime otherwise
________
And again an example why one should double check :D
> lsof should be correctly detected now

- tomb
Tip for zsh: use `${=variable}` only when **absolutely** necessary
> Totally fixed spaces handling in tomb and tomber

- extras/test/runtests
- tomb
This fixes issue #247.
I tried to do things in the most straightforward and simple way, and attempted to follow the code conventions in `tomb` and `runtests`. Please let me know if there is anything I should improve!
Tomb can now open read-only Tomb files and mount them as a read-only file system. If the string `ro` is detected anywhere in the value of the `-o` option, Tomb skips the check that makes sure the Tomb file is writable.
I've added a test that prepares a test tomb file called testro.tomb, removes its write permissions, and tries to open it as a read-only file system with `-o ro,noatime,nodev`. I made this test before changing anything else, then changed the code so it succeeded. I also did some manual testing after everything seemed to be working.
Prepare test Tomb file:
$ …
> Open non-writable Tomb files with "read only " mount option

- extras/test/runtests
- tomb
This PR tries to fix the few issues related to the GPG option in PR #244.
The new features are:
* Support for GPG default key (by default). Tomb now always use the default-key unless the `-r` (or `-R`) option provides a recipient.
_Note_: when using the default key, the recipient is not hidden.
* The use of hidden recipient is activated when the recipients are provided using the `-R` option. Otherwise, when using the `-r` option, the recipient will not be hidden in the encrypted tomb key.
_Note_: I implemented this feature because it does not always make sense to hide the recipient. Moreover, it adds a layer of complexity for the user: They must provide the (long) recipient, if the tomb is shared side problem appears.
Feedback are welcome. If you do not like a thing in the implementation …
> Options for GnuPG Key

- extras/test/gnupg/gpg.conf
- extras/test/runtests
- tomb
This PR does three things:
* Remove `--shared`. See #252
*  Support for gpg encrypted tomb key loaded from stdin. See #255
* Fix a few issues regarding GPG default key. 
- Remove `--no-options` gpg option when using GPG key.
- Improve gpg default key tests
To use the default key, `~/.gnupg/gpg.conf` needs:
```
default-key <keyid>
default-recipient-self
```
Or
```
default-recipient <keyid>
```
Otherwise the first key in the keyring is used.
They will be other changes in the future regarding wrong use of `-g` option and issue with pinentry. I don't know when they'll be ready, they could be the purpose of an other PR. # #
> Options for GnuPG Key - 2

- .travis.yml
- extras/test/.gitignore
- extras/test/00_create.sh
- extras/test/10_operations.sh
- extras/test/20_recipients.sh
- extras/test/30_kdf.sh
- extras/test/40_regression.sh
- extras/test/50_integrity.sh
- extras/test/60_resize.sh
- extras/test/65_passwd.sh
- extras/test/70_qrencode.sh
- extras/test/75_hooks.sh
- extras/test/80_steganography.sh
- extras/test/90_setkey.sh
- extras/test/Makefile
- extras/test/aggregate-results
- extras/test/setup
- extras/test/sharness
This PR replace the existing handmade tomb test suite by the [sharness](https://github.com/chriscool/sharness) test suite. See #259. It provides the portage of all the tests from the old test suite to the new one.
**The new `extras/test` architecture is the following:**
* `sharness`, `aggregate-results`, `Makefile` The test suite
* `setup` Internal test configuration file. It has to be sourced by all test-scripts.
* `*.sh` The tests scripts
**The tests scripts are the following:**
* `00_create.sh` tomb dig, forge, lock    
* `10_operations.sh` Basic operations on tomb: open, close
* `20_recipients.sh` GPG key related tests
* `30_kdf.sh` KDF related tests
* `40_regression.sh` Regression tests
* `50_integrity.sh` Integrity tests
* `55_index.sh`    index & search (TODO)
* `60_resize.sh` tomb …
> Replace the test suite by the sharness test suite

- extras/test/10_operations.sh
- extras/test/Makefile
- extras/test/close_block.c
- extras/test/setup
- tomb
PR for the missing stuff since the reintroduction of lsof for slam operation, which means it is now included in --version and a testcase was added.
Thanks to @roddhjav for help with it.
Any missing stuff, or something that should be changed, etc?
> Missing lsof stuff

- doc/tomb.1
- tomb
Small refactoring of `post-hooks` now renamed to `exec-hooks` accepting two callbacks states: `open` and `close` that are passed as string arguments to the script or executable in place. Documentation updated accordingly.
> Exec hooks

- tomb
Checking if a /dev/mapper/tomb* is still present in the
output of mount after umounting binded directories.
Addresses issue #265
> Double check after umounting bind directories

- README.md
- doc/tomb.1
- tomb
Slam wasn't working well at least in my installations. When looking at its code, I got a bit disgusted. This PR refactors it so that:
1. slam is a separate function calling umount_tomb() at the end, not the contrary
2. there is a new command 'ps' to list all processes currently using tombs
3. there are less calls to external utilities
> Slam refactor

- tomb
As debated in issue #282 Zsh introduced a bug in v5.3.1 which briefly affected
our mechanism for closing tombs. The bug is fixed, but while investigating the
issue @aude realised there can be a better way to apply this regex for the
detection of mounted volumes on distro dependent /run/media/$USER paths.
This change drops usage of the regex optional module in Zsh to use the built-in
=~ comparison and improves the match using round parenthesis. It may fix the
close command on some distributions.
> drop zsh/regex module in favor of =~

- Makefile
- tomb
This commit will use `shred` (which is part of util-linux) instead of `wipe`, which is yet another external dependency.
> use shred instead of wipe

- tomb
This fixes a mount-related functionality (finding the volume label) in new versions of util-linux, that since v2.30 does not list anymore volume labels with its mount -l command. Since findmnt needs sudo to list labels, this also introduces the need for sudo in more commands: is_valid_tomb(), list, index and search. The issue was examined in PR #283 and this is a rebase of it.
> Replace 'mount -l' with 'findmnt'

- extras/test/40_regression.sh
- extras/test/Makefile
- extras/test/aggregate-results
- extras/test/setup
- tomb
Hi @jaromil 
As it seems you are going to do a release soon, there are a few fixes I have on my local system and that can be merged quite easily:
* Use the zsh function `is-at-least` instead of `=~` to check program version.
* Support non-standard zsh location in the test suite. See #283
* Remove useless cleanup in test setup.
Regards,
Alex
> Fixes: version check & tests

- doc/tomb.1
- tomb
This reverts commit 843b7fdfc4c125065d31cc11cff8a994ed680bd4
and refers to various issues, among them #268
On the long term its easy to realise how this is a usability feature for most
users, so we just provide a new '-p' flag to preserve ownership on open.
> restored change of ownership on tomb's contents

- tomb
Please add support for pinentry-qt5. The pinentry-qt4 is not used anymore in some distros.
> Added pinentry-qt5 support

- tomb
avoid code duplication since all pinentry impelmentation need the same sequence of assuan commands, according to suggestion in #303 by @Narrat
> put assuan commands to pinentry into a single function

- extras/gtk-tray/tomb-gtk-tray.c
Default behavior for tomb is to mount the volume filename.tomb in /media/filename.
Ubuntu 16.04, Tomb 2.5
> Fix mounted volume default path

- .travis.yml
- extras/kdf-keys/Makefile
- extras/kdf-keys/pbkdf2.c
- extras/kdf-keys/test.sh
Fixes this issue: https://github.com/dyne/Tomb/issues/307
There was also a test in `extras/kdf-keys` that was failing (it was assuming that the NULL byte could be part of the password), this PR makes the test to pass as well.
Some tests have been added checking that passwords are not split if they have whitespaces and checking len limits for passwords
It also enables the execution of tests in `extras/kd-keys` in travis' build
> Fixes a problem reading passwords when using the kdf wrapper  

- extras/test/10_operations.sh
- tomb
Collects the stats of tomb keys and tomb files then restore them when
Tomb exits. Can be extended to any file opened by Tomb. See #266
> Track access/modification time of sensitive files

- tomb
This check would've caught the invalid header being generated in #331.
> Check for KDF header in is_valid_key

- tomb
Change to print messages to stdout by default, and stderr if the return code for `_msg` is non-zero.
Also check if the stream being printed to is a tty and otherwise disable escape sequences.
Update: the commit effecting the following was excluded from this PR as it caused tests to fail.
> Finally, change `_print "\000"` to `_print ""` as `less` (for example) doesn't like the former and they seem to be equivalent.
> Overhaul message printing

- tomb
`tomb lock` suggested command was missing "-k" flag; although this can be inferred from other commands, it's likely worth having it spelled out plainly
> Update suggested command with missing flag

- .travis.yml
- Dockerfile
- extras/install_cloakify.sh
- extras/install_sphinx.sh
- extras/test/00_create.sh
- extras/test/10_operations.sh
- extras/test/60_resize.sh
- extras/test/65_passwd.sh
- extras/test/75_hooks.sh
- extras/test/90_setkey.sh
- extras/test/setup
- extras/test/sphinx.cfg
- tomb
Fixes #306 
**Summary**:
- updated **ask_password** and adjacent logic to support retrieving password via sphinx
- added sphinx opts to commands that expect password
- added sphinx installation script (also copies default sphinx/oracle config for testing)
- created base dockerfile
- added tests for commands using sphinx
Note for the users of this feature: sphinx (client) needs to be in quiet mode to work with tomb, verbose will disrupt picking up the password properly. As suggested in sphinx's description, **do not** run sphinx and oracle on the same machine (this only gives a false feeling of security). The configuration included in extras is for testing purposes only.
> Pitchforked sphinx integration

- doc/tomb.1
- extras/android/tomb
- extras/test/90_setkey.sh
- extras/test/runtests
- extras/test/setup
- tomb
there is no need to default to a blocking source of random,
since /dev/random doesn't improves the quality of randomness in Linux
fix #349
> switch default random source to /dev/urandom

- tomb
this restyles some code introduced by the sphinx feature and tries to fix parse
errors reported in issue #357
> rewrite some conditionals for less ambiguity

- doc/tomb.1
Hi,
I've fixed some stuff in linux manpage:
* replaced old "post-hooks" with the new "exec-hooks"
* Firefox example - Firefox doesn't start if specified profile directory doesn't exist
> Fix manpage

- tomb
This code addresses issue #375 by forcing all verbose messages to write to STDERR.
> Write all debug messages to stderr to avoid polluting stdout.

- tomb
> Allow pinentry to fail, so long as the password comes through.

- INSTALL.md
Fixed a visual error in `INSTALL.md`
The table was not showing properly.
> Fix table syntax Markdown

- tomb
Fixes https://github.com/dyne/Tomb/issues/385. Note that affected users will have to decrypt their existing tombs using the password `tomb [W] Detected DISPLAY, but only pinentry-curses is found.`.
Should I append KNOWN_BUGS in this PR, or would a maintainer like to write that part?
> Use _verbose for pinentry-curses in ask_password

- tomb
Change the mapper path using a hash of the tomb file path,
making it unique and reproducible to check if tomb is in use.
Check happens inside the new render_mapper() function which is
executed right after the key file opening.
Provides a fix for #387 and #326 as well signaled in https://github.com/roddhjav/pass-tomb/issues/27
> improve the check if a tomb file is in use

- tomb
also changes to priority order of invokation and some code cleanups and
indentations. Invokation order is now:
- WAYLAND? pinentry-gnome3
- X11?
1. pinentry-x11 (distro specific wrapper)
2. pinentry-gtk2 (legacy, removable)
3. pinentry-gnome3
4. pinentry-qt5
5. pinentry-qt4
- NO DISPLAY? pinentry-curses
address #381
> updated pinentry invokation to include wayland

- tomb
Affected the use of Tomb without DISPLAY and pinentry-curses.
Fixes #393
> Fix typo calling pinentry_assuan_getpass

- extras/kdf-keys/Makefile
Added `$(CFLAGS)` environment variable in the kdf-keys makefile to allow users to specify additional build flags.
> Read CFLAGS in kdf-keys makefile

- extras/install_sphinx.sh
- extras/test/Dockerfile
- extras/test/sphinx.cfg
- tomb
- Installing **pwdsphinx** from pip3 still results in incorrect entrypoint, so now we're getting both **libsphinx** and **pwdsphinx** from the same place (more consistent)
- **sphinx** no longer _requires_ SSL cert, but fails without it (`check_hostname requires server_hostname`, seems like check_hostname in SSL context [stays True](https://github.com/stef/pwdsphinx/blob/0b2ae15ada58010469d9cb91c43aebf3ba9a893b/pwdsphinx/sphinx.py#L64) in that case); **oracle** requires it anyway so I kept the dummy cert creation in the sphinx installation script
- added chimaera repo to get the required version of libsodium (as I mentioned, compiling it from source takes a while)
- updated expected text for when sphinx command fails (it is no longer `ValueError: fail`)
> Fix configs and dockerfile to enable sphinx in tests

- tomb
this may fix whitespace issues referred by #433 and previously related
to bind mounts as of #222
> wrap all references to $tombmount string into quotes

- doc/tomb.1
- tomb
following many requests, here is support for argon2 KDF to be switched
on using --kdftype argon2 (--kdf iterations --kdfmem memory)
effective memory required is 2^memory KiB, defaults to 18 (262 MiB)
number of iterations are still specified as --kdf argument
requires the argon2 reference C implementation from P-H-C
also requires tomb-kdb-pbkdf2-gensalt in extras/kdf-keys
example usage:
tomb forge -k argon.key --kdf 10 --kdftype argon2
> KDF support for argon2 memory intensive algorithm

- tomb
If there is no free loop device, the call of loopsetup -f will create one and return it. For this it needs privilege escalation.
It doesn't need those, if there is already an used device, but that cannot be guaranteed.
Closes #436
________________
Just readds the logic before the change. Maybe there is a better way to check for loop support?
> lo_mount: check for loop support needs privilege escalation

- extras/android/tomb
- extras/translations/de.po
- extras/translations/es.po
- extras/translations/fr.po
- extras/translations/it.po
- extras/translations/ru.po
- extras/translations/sv.po
- extras/translations/tomb.pot
- extras/translations/zh_Hans.po
- tomb
Just a little typo: `Succesfully` -> `Successfully`
Thank you for the great work!
> fix typo Succesfully -> Successfully

- doc/tomb.1
- tomb
The --filesystem option can be used  to  specify
an  alternative  filesystem used to format the tomb, in place of the default "ext4".
Beside "btrfs" now the following parameters to --filesystem are supported:
"ext3"    using operating system defaults
"ext4"    using operating system defaults
"btrfs"   for tombs >= 47MB using operating system defaults
"btrfsmixedmode"    for tombs >=18MB btrfs mixed mode (see mkfs.btrfs(8))
"ext3maxinodes"     ext3 with a maximum of inodes (for many small files)
"ext4maxinodes"     ext4 with a maximum of inodes (for many small files)
These changes help use scenarios in which there is a great number of small files and/or directories in a small filesystem, like e.g. the pass-tomb extension to pass.
> cmd lock: extend parameters to --filesystem

- tomb
As far as I can see nothing in `tomb` directly requires `python2`.
And the check itself wasn't used anywhere?
Unless it is parsed from somewhere else? Related to tests?
If not, why not getting rid of it?
> Remove unused check on python2

- extras/gtomb/gtomb
1. replaced soft with hard tabs to maintain code standard;
2. inserted a "wait" statement in the dig, forge, lock and open functions;
3. spelling standardization (canceled to cancelled);
4. simplified the call to MONMORT icon inside zenity functions;
5. zenity warning function changes;
6. fixed missing dots.
My previous PR #465 (merged) used soft tabs, because my editor uses soft tabs, but gtomb itself uses hard tabs. Now uniform.
Some messages like `Success: Tour tomb has been dug in ...` was appearing BEFORE the tomb was actually dug. With a `wait` statement the message appears AFTER the tomb has been created. Similar situations occurred in forge, lock and open functions.
Most of text is in english British, Canadian, Australian (_cancelled_) but a few times "cancelled" appears spelled …
> Modest extras/gtomb update

- doc/tomb.1
Fixed wrong information about `--kdfmem`.
```
2^18 = 262,144 kilobytes = 250 MiB
```
Not 262 MiB as stated before.
> Manpage update

- tomb
Tomb is an old tool and uses `mlocate` for searching/indexing. But modern systems have replaced `mlocate` with `plocate`. On these systems (such as Linux Mint 21.1 and Ubuntu 22.04) the `tomb index` or `tomb search` commands are broken, user receives message:
```
Index command needs 'mlocate' to be installed.
```
To fix this issue i have changed lines with:
```
[[ "$updatedbver" =~ "mlocate" ]] || {
_failure "Index command needs 'mlocate' to be installed." }
```
To:
```
[[ "$updatedbver" =~ "locate" ]] || {
_failure "Index command needs 'mlocate/plocate' to be installed." }
```
Now both systems (with mlocate or plocate) works fine.
[plocate](https://plocate.sesse.net/) is backwards-compatible with mlocate, and is much faster and more efficient than mlocate.
In fact you don’t have a choice …
> Tomb accepts also plocate for search/index (not only mlocate)

- extras/kdf-keys/hexencode.c
I know `tomb-kdb-hexencode` was never used (as revealed in issue #471), but I recently compiled the kdf-keys and got this warning:
This PR change `%x` to `%s` as should be, as explained in [TutorialsPoint - C library function - sscanf()](https://www.tutorialspoint.com/c_standard_library/c_function_sscanf.htm). 
No need, i know. Just to keep things working.
> Fix hexencode compilation warning caused by wrong type

- extras/translations/Makefile
- extras/translations/README.md
- extras/translations/es.po
- extras/translations/fr.po
- extras/translations/it.po
- extras/translations/pt_BR-2.10.po
- extras/translations/pt_BR.po
- extras/translations/ru.po
- extras/translations/tomb-2.10.pot
Where to start from?
> One request before merging, which should be easy to do: can you please also update the .po translations with this detail? so we keep them aligned.
Done. I used a script to print help output out of PO files and check all them:
```sh
#!/usr/bin/env zsh
clear
egrep -A 141 'Syntax:' $1 | 
egrep -v "^(#|msgid|\s*$)" | 
sed 's/msgstr \"//g' | 
sed 's/\" / /g' | 
grep -v "^\"" |
sed 's/\"$//g'
```
Not important, just saying.
Related to issue #482. I have translated to `pt_BR` before Weblate was created, sorry. But thank you for that.
Hard to explain, better to read the ne created README for extras/translations folder. It's all very well explained there.
This is a huge point, ALL translations in `extras/translations` are based upon `Tomb 2.3`, _not_ the `current 2.10` or …
> Translations severe update

- tomb
The operator < compares two strings lexicographically resulting in that a 100MB tomb is considered smaller than 47MB or 18MB.
Closes #489
__________
Took the liberty and created the PR which incorporates the fix for #489
> Fix operators to compare numerically, not lexicographically

- doc/tomb.1
________________
Closes #490
Took the liberty and prepared the supplied patch
Before:
```
Supported filesystems for --filesystem:
"ext3"    using operating system defaults
"ext4"    using operating system defaults
"btrfs"   for tombs >= 47MB using operating system defaults
"btrfsmixedmode"    for tombs >=18MB btrfs mixed mode (see mkfs.btrfs(8))
"ext3maxinodes"     ext3 with a maximum of inodes (for many small files)
"ext4maxinodes"     ext4 with a maximum of inodes (for many small files)
```
After:
```
Supported filesystems for --filesystem:
ext3           using operating system defaults
ext4           using operating system defaults
btrfs          for tombs >= 47MB using operating system defaults
btrfsmixedmode for tombs >=18MB btrfs mixed mode (see mkfs.btrfs(8))
ext3maxinodes  ext3 …
```
> Fix some table mimicking lines to honor the recent line width

- tomb
_cat is not defined/autoloaded anywhere, so use plain unix cat utility to avoid getting "command not found" error
> Use cat instead of _cat

- doc/tomb.1
Under `bind-hooks`, in the line:
```
the tomb. The files and directories will be be made directly
```
Word `be` appears twice.
And in PASSWORD INPUT, added linke breaks to fit 80 columns. It was a "very long line". Just keeping the document standard.
Better formatting of .EX/.EE macros adding indentation.
Replaced `mlocate` with `mlocate/plocate`. Since commit 59d7331 added plocate as a possibility.
> manpage: typo fix, column formatting, .EX/.EE macros indentation etc

- tomb
Parsing the output from lsof had possibilities for race conditions. Either due to short lived processes or issuing "tomb ps" from a terminal which cwd is from inside the tomb. This would for example list available users on the system. To avoid this use the lsof output directly.
In the future formatting could be reintroduced via commands like "lsof +D "$tombmount" -F Lc" or "lsof +D "$tombmount" -F Lc0".
This fixes #503
___________
The lazy solution for #503. For me the output is enough :D
Example:
```
$  ./tomb ps
tomb (*) Listing processes running inside all open tombs...
COMMAND  PID   USER  FD   TYPE DEVICE SIZE/OFF NODE NAME
zsh     1221 omnius cwd    DIR  254,0    12288    2 /run/media/omnius/Z
```
This doesn't touch `slam_tomb()` which in general uses the same logic and should …
> list_processes: use lsof to list processes

- doc/tomb.1
Somehow this section existed two times in the man page with similar information.
_____________________________
Dunno how accurate the comment in regards to `gpg-agent` is (especially the last sentence).
But I adjusted it somewhat in regards to Wayland and the EOL of GTK2 which makes `pinentry-gtk2` not the first choice anymore. Some distributions are actively working on removing GTK2 entirely.
> Man: merge section on Password Input

- extras/test/75_hooks.sh
- tomb
Cryptsetup is since 1.3.0 capable of setting up a loop device if the device argument is a file.
This has the additional benefit that those loop devices will get the AUTOCLEAR flag (available with Linux 2.6.25). This means those loop devices will be closed as soon their're unused (on luksClose).
_____________________
Read about something unrelated, stumbled upon cryptsetup usage without explicit losetup fiddling and thought maybe this is something for tomb to adopt.
Alternatively `lo_preserve()` could be dropped and respective changes at other places still could apply. `losetup -d` removes devices lazily. If it cannot be closed it won't report `EBUSY` anymore, but instead set `AUTOCLEAR` (since Linux 3.7). Status can be seen via `losetup --list`.
Would be nice to get rid of `lo_mount` (now …
> Avoid manual handling of loop devices

- tomb
Two things get in this PR addressed:
In https://github.com/dyne/tomb/pull/504 list_processes() got reworked in a way to avoid parsing process
output as this had interesting side-effects.
Back then I mentioned the same behaviour existing in slam_tomb() which
should probably be changed too. This PR addresses that.
Firstly it will use list_processes() from within slam_tomb(), as this is
in principal overlapping functionality. For this list_processes() needed
to be adjusted. It now has a return value which can indicate if there
were processes.
Secondly the order of execution was changed in slam_tomb(). Before it
would process one process and work through the signals until this
process was killed. Now it will take a signal and issue a kill for all
processes found.
In general umount_tomb and …
> Rework slam function

- tomb
Namely /run/media/$USER.
The mount point itself is owned by root, therefore one needs to know the name of the mountpoint to change to the location. Other tools for mounting media like udisksctl set ACL to allow the owner to use it normally (autocompletion and such).
Fixes #461
_______________
To get the solution for the named issue going.
There were some undecided points and maybe with some changed code this can go on further.
Therefore this PR is only a draft. Request for comments
> mount_tomb: make use of ACL in specific locations

- tomb
egrep and fgrep are deemed obsolete and usage issues a warning since a few versions. To quote the respective notification:
7th Edition Unix had commands egrep and fgrep that were the counterparts of the modern ‘grep -E’ and ‘grep -F’. Although breaking up grep into three programs was perhaps useful on the small computers of the 1970s, egrep and fgrep were deemed obsolescent by POSIX in 1992, removed from POSIX in 2001, deprecated by GNU Grep 2.5.3 in 2007, and changed to issue obsolescence warnings by GNU Grep 3.8 in 2022; eventually, they are planned to be removed entirely.
Closes #553
> change egrep to grep -E

- extras/translations/de.po
- extras/translations/es.po
- extras/translations/fi.po
- extras/translations/fr.po
- extras/translations/it.po
- extras/translations/pt_BR.po
- extras/translations/ru.po
- extras/translations/sv.po
- extras/translations/tomb.pot
- extras/translations/zh_Hans.po
- tomb
Fixes #555
__________________________
Done as draft as long not all translation files are updated
> Sync translations with tomb script

- tomb
This change rewrites the custom `pinentry` search code to instead be a modified form of the standard `/usr/bin/pinetry` fallback script. The prior behaviour could not handle cases where a `pinentry` executable existed but was not actually usable. Now it checks using `ldd` for if an executable is functional or not. Additionally rewritten to be more clear and easier to extend with newer `pinentry` backends.
`make test` was ran, and it passed the main usability tests for password entry. As my testing system uses swap it failed during the KDF test from an error from swap being enabled; I did not attempt further tests with swap disabled.
This partially fixes Issue #542.
Note: This adds a new dependency on `ldd`. For systems without `ldd` installed (such as `musl` systems) they either need to …
> Rewrites `pinentry` find code to be more resilient

- tomb
In general variables are added as separate arguments. This avoids them appearing in translateable strings.
____________
TBD: regeneration of the strings
> Message strings: adjust string where variable was inline

- tomb
One of the changes introduced with 6aff011 got overwritten by ebf2fb6 This commit corrects that.
> index: reinstate updatedb check in index_tombs()

- doc/tomb.1
Debian's lint tool complained about "allows to" in line 291, instead "allows one to" would be correct.
> Fix typo in manual page

- doc/tomb.1
- tomb
This allows to specify a specific pinentry program which is tried first while finding a working pinentry program.
For input is only the part needed after "pinentry-". This isn't a general option to specify something completly different as password input (yet).
The update to the manpage includes the new option and an update to the pinentry section. With the way how pinentry is nowadays detected, the manual force of a specific pinentry via symlink shouldn't be encouraged. And if a specific one should be used, one can use now the new option.
____________
Doesn't really help with the big ToDos in `ask_password()`, but allows in theory the usage of pinentries like `wayprompt` or `pinentry-bemenu`.
Did take a look into adding the wrapper.. but this is not a small change. Especially with all the …
> Add option --pinentry
